config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root :to => 'users#index'

  resources :twitches
  resources :followers

end

app/models/follower.rb
class Follower < ActiveRecord::Base

  belongs_to :user

end

app/models/twitch.rb
class Twitch < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :twitches
  has_many :followers

  after_create :send_welcome_email

  def twitch_search
    results = []
    Twitch.all.each do |twitch|
      if twitch.content.include? self.email
        results << twitch
      end
    end
    results
  end

  def mentions
    mentions = []
    twitch_search.each do |twitch|
      mentions << [User.find(twitch_search.first.user_id), twitch]
    end
    mentions
  end

  private

  def send_welcome_email
    UserMailer.signup_confirmation(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    twitches_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  before_filter :authenticate_user!

  def new
    @follower = Follower.new
    @user = current_user
    @users = User.all
  end

  def create
    @follower = Follower.new(follower_params)
    if @follower.save
      respond_to do |format|
        format.html { redirect_to twitches_path }
        format.js
      end
    else
      render 'new'
    end
  end

def destroy
    @follower = Follower.find(params[:id])
    @follower.destroy
    redirect_to twitches_path
  end

private
  def follower_params
    params.require(:follower).permit(:user_id, :follower_id)
  end

end

app/controllers/twitches_controller.rb
class TwitchesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @user = current_user
    @twitches = @user.twitches
    @mentions = @user.mentions
    @followers = @user.followers
  end

  def new
    @twitch = Twitch.new
    @user = current_user
  end

  def create
    @twitch = Twitch.new(twitch_params)
    if @twitch.save
      respond_to do |format|
        format.html { redirect_to twitches_path }
        format.js
      end
    else
      render 'new'
    end
  end

  def edit
    @twitch = Twitch.find(params[:id])
  end

  def update
    @twitch = Twitch.find(params[:id])
    if @twitch.update(twitch_params)
      redirect_to twitches_path
    else
      render 'edit'
    end
  end

  def destroy
    @twitch = Twitch.find(params[:id])
    @twitch.destroy
    redirect_to twitches_path
  end

  private
  def twitch_params
    params.require(:twitch).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:index]

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followers/_follower.html.erb
<li><%= "#{follower.id}" %>
        <%= link_to "Delete", follower_path(follower), :data => {:confirm => "You sure?", :method => "delete"} %>
    </li>

app/views/followers/_form.html.erb
<% if @follower.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @follower.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @follower, remote: true do |f| %>
  <div class="form-group">
    <%= f.collection_select :user_id, @users, :id, :email, include_blank: true %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :follower_id, :value => @user.id %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/followers/create.js.erb
$('#new_follower').remove();
$('#follow_someone').show();
$('#followers').append('<%= j render(@follower) %>');

app/views/followers/new.html.erb
<hr>
<%= render 'form' %>
<br>
<%= link_to "Cancel", twitches_path, :class=> "btn btn-success" %>

app/views/followers/new.js.erb
$('#follow_someone').hide().after('<%= j render("form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/twitches/_follower.html.erb
<li><%= "#{follower.user_id}" %>
        <%= link_to "Delete", follower_path(follower), :data => {:confirm => "You sure?", :method => "delete"} %>
    </li>

app/views/twitches/_form.html.erb
<% if @twitch.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @twitch.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @twitch, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/twitches/_mention.html.erb
<% @mentions.each do |mention| %>
  <li><%= mention[0].email %> : <%= mention[1].content %> </li>
<% end %>

app/views/twitches/_twitch.html.erb
<li><%= "#{twitch.content}" %>
        <%= link_to "Delete", twitch_path(twitch), :data => {:confirm => "You sure?", :method => "delete"} %>
    </li>

app/views/twitches/create.js.erb
$('#new_twitch').remove();
$('#add_twitch').show();
$('#twitches').append('<%= j render(@twitch) %>');

app/views/twitches/index.html.erb
<h1>Welcome to Twitcher - Your Source for Narcissistic Distraction </h1>
<h3>My Twitches</h3>
<ul id="twitches">
  <%= render @twitches %>
</ul>
<br>
<%= link_to "New Twitch", new_twitch_path, :class=> "btn btn-success", id: "add_twitch", remote: true %>
<br>
<h3>Twitches That Mention Me</h3>
<br>
<ul id="mentions">
  <%= render partial:"mention" %>
</ul>
<br>

app/views/twitches/new.html.erb
<h1> New Twitch - Your Chance to Make Others Aware of <em>Your</em> Greatness! </h1>

<hr>
<%= render 'form' %>
<br>
<%= link_to "Cancel", twitches_path, :class=> "btn btn-success" %>

app/views/twitches/new.js.erb
$('#add_twitch').hide().after('<%= j render("form") %>');

app/views/users/index.html.erb
<div id = "intro">
  <h1>Welcome to Twitcher - Your Source for Narcissistic Distraction </h1>
  <h3>What it is:<h3>
  <h5>A way of accumulating followers who will hang on your every word, and a way of finding people who will randomly interrupt your life with irrelevant (but fascinating!) messages.</h5>
  <h3>Why you should sign up or log in<h3>
  <h5>Because it's all about you.</h5>
  <h3>Will it cost me anything?</h3>
  <h5>Only your time and sense of perspective.  Money-wise it's free, because we monetize your data.</h5>
</div>